services:
  linux-builder:
    image: ghcr.io/rpdevs-builds/runner-linux-builder:latest
    container_name: kodi-linux-builder
    restart: always
    environment:
      - GH_OWNER=RPDevs-Builds
      - GH_TOKEN=${GH_PAT}
      - RUNNER_NAME=kodi-local-linux-v2
      - RUNNER_LABELS=self-hosted,linux64
    volumes:
      - /mnt/largedata/github_runners/linux-builder/work:/home/runner/_work
      - /mnt/sharedroot/appdata/github_runners/linux-builder/outputs:/home/runner/outputs
    security_opt:
      - no-new-privileges:true

  addon-builder:
    image: ghcr.io/rpdevs-builds/runner-addon-builder:latest
    container_name: kodi-addon-builder
    restart: always
    environment:
      - GH_OWNER=RPDevs-Builds
      - GH_TOKEN=${GH_PAT}
      - RUNNER_NAME=kodi-local-addon-v2
      - RUNNER_LABELS=self-hosted,lightweight
    volumes:
      - /mnt/largedata/github_runners/addon-builder/work:/home/runner/_work
      - /mnt/sharedroot/appdata/github_runners/addon-builder/outputs:/home/runner/outputs
